name: Build Taco Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.biighunter }}
          password: ${{ secrets.11236939.Smh }}

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/your-image-name .

      - name: Push Docker image to Docker Hub
        run: docker push your-dockerhub-username/your-image-name
